books/urls.py
from django.urls import path

from .views import BookView, BookDeleteView, BookUpdateView

urlpatterns = [
    path("", BookView.as_view(), name="books"),
    path("<int:pk>/delete/", BookDeleteView.as_view(), name="book-delete"),
    path("<int:pk>/edit/", BookUpdateView.as_view(), name="book-edit"),
]

books/models.py
import calendar
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class BooksManager(models.Manager):
    @staticmethod
    def get_books_data(user) -> dict:
        """
        Build dict object with year, month and day info.
        :return: dict(int: dict(int, dict(int: list(int, int)))
        {'2021': {'January': {'days': ['10', '13', '13', '17'], 'num_pages': 48}}
        """
        books = Books.objects.filter(user=user)
        data = {}

        for book in books:  # create dict year: month: day
            date = str(book.date).split("-")  # year, month, date
            date[1] = str(_(calendar.month_name[int(date[1])]))  # 10 -> May
            num_pages = int(book.num_pages)

            if date[0] in data:
                if date[1] in data[date[0]]:  # month in data[year]
                    data[date[0]][date[1]]["days"].append(date[2])
                    data[date[0]][date[1]]["num_pages"] += num_pages
                else:  # month not in data[year]
                    data[date[0]].update(
                        {date[1]: {"days": [date[2]], "num_pages": num_pages}}
                    )
            else:  # year not in data
                data[date[0]] = {date[1]: {"days": [date[2]], "num_pages": num_pages}}

        return data

    @staticmethod
    def get_years_of_reading(user: User) -> list:
        """
        :return: Sorted list that contains years from the
         top level of the expression.
        """
        books_date = Books.objects.filter(user=user).values_list("date", flat=True)
        years = {str(date.year) for date in books_date}
        return sorted(years)


class Books(models.Model):
    POOR = 1
    AVERAGE = 2
    GOOD = 3
    VERY_GOOD = 4
    EXCELLENT = 5

    PAPER = 1
    E_BOOK = 2
    AUDIO = 3

    Books_type_CHOISES = (
        (PAPER, _("Paper Book")),
        (E_BOOK, _("Ebook")),
        (AUDIO, _("Audio Book")),
    )

    Rating_CHOICES = (
        (POOR, _("Poor")),
        (AVERAGE, _("Average")),
        (GOOD, _("Good")),
        (VERY_GOOD, _("Very Good")),
        (EXCELLENT, _("Excellent")),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    author = models.CharField(max_length=256)
    num_pages = models.IntegerField(default=0)
    date = models.DateField(default=datetime.date.today)
    type_of_book = models.IntegerField(choices=Books_type_CHOISES, default=1)
    favorite_rank = models.IntegerField(choices=Rating_CHOICES, default=5)
    review = models.TextField(blank=True)

    is_active = models.BooleanField(default=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    update_at = models.DateTimeField(auto_now_add=False, auto_now=True)

    objects = BooksManager()

    def __str__(self):
        return "{}, {}".format(self.name, self.author)

    class Meta:
        verbose_name = "Book"
        verbose_name_plural = "Books"

    def get_list_rating(self):
        """
        Building ratting for book.
        :return: dict{'name_book':[list of max numbers 1, 2, 3, 4]}
        """
        books = Books.objects.filter(user=self.user, is_active=self.is_active)
        return {
            book.name: [inx for inx in range(1, book.favorite_rank + 1)]
            for book in books
        }

    @staticmethod
    def get_max_year_of_book(user) -> str:
        """
        Return last year when the book was created or "all".
        """
        books = Books.objects.filter(user=user, is_active=True)
        max_year = "all"
        if books.exists():
            max_year = str(books.latest("date").date.year)
        return max_year

    @staticmethod
    def get_book_type_names() -> list:
        book_types = Books.Books_type_CHOISES
        name_types = [str(i[1]) for i in book_types]
        return name_types

    @staticmethod
    def get_type_counts() -> int:
        book_types = Books.Books_type_CHOISES
        return len(book_types)

books/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import Books


class BookForms(forms.ModelForm):
    class Meta:
        model = Books
        exclude = ["user", "is_active"]

        widgets = {
            "name": forms.TextInput(
                attrs={
                    "placeholder": _("Name Book*"),
                }
            ),
            "author": forms.TextInput(
                attrs={
                    "placeholder": _("Author*"),
                }
            ),
            "date": forms.DateInput(
                attrs={
                    "data-toggle": "datepicker",
                }
            ),
            "review": forms.Textarea(
                attrs={
                    "rows": "8",
                    "placeholder": _("Review"),
                }
            ),
        }

    def clean_author(self):
        data = self.cleaned_data["author"]
        data = data[0].upper() + data[1:]
        return data

    def clean_name(self):
        data = self.cleaned_data["name"]
        data = data[0].upper() + data[1:]
        return data

books/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import TemplateView, DeleteView, UpdateView
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils.translation import ugettext_lazy as _

from .forms import BookForms
from .models import Books
from .services import get_book_list_rating_by_user


class BookView(LoginRequiredMixin, TemplateView):
    template_name = "books/books.html"
    model_form = BookForms

    def get_form(self):
        return self.model_form(data=self.request.POST or None)

    def get_books(self, year, order_by):
        filter_kwargs = {
            "user": self.request.user,
            "is_active": True,
        }
        if year.isnumeric():
            filter_kwargs["date__year"] = int(year)

        return Books.objects.filter(**filter_kwargs).order_by(order_by)

    def get(self, request, *args, **kwargs):
        user = request.user
        max_year = Books.get_max_year_of_book(user)
        year = request.GET.get("year", max_year)

        # order_by if order_by else -date
        order_by = request.GET.get("order_by", "-date")

        # filtering books
        books = self.get_books(year=year, order_by=order_by)
        years = Books.objects.get_years_of_reading(user)
        book_list_rating_by_user = get_book_list_rating_by_user(user)

        kwargs.update(
            {
                "form": self.get_form(),
                "books": books,
                "years": years,
                "current_year": year,
                "book_list_rating_by_user": book_list_rating_by_user,
            }
        )

        return super().get(request, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.get_form()

        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            success_message = _("You book was successful added.")
            messages.success(request, success_message)
            return HttpResponseRedirect(reverse("books") + "?signal=True")

        kwargs.update({"form": form})
        return super().get(request, *args, **kwargs)


class BookDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Books
    success_message = _("You book was successful deleted.")
    success_url = reverse_lazy("books")

    def get(self, request, *args, **kwargs):
        """
        Overwrite get because we make deletion by link on books page and
        we don't need confirmation page for deletion.
        """
        return self.post(request, *args, **kwargs)


class BookUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    form_class = BookForms
    model = Books
    template_name = "books/book-edit.html"
    success_message = _("You book was successful changed.")
    success_url = reverse_lazy("books")

templates/books/book-edit.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{% block title %}
    <title>My books | Edit | {{ book.author }}, {{ book.name }}</title>
{% endblock %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'less/books.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'less/plugin/datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <section class="booksListSection">
        <div class="container fix-width">
            <div class="booksListTable">
                <form method="POST">
                    {% csrf_token %}
                    <div class="booksListRowAdd">
                        <div class="booksListRowAddStep one edit">
                            <span>{{ form.name }}</span>
                            <span>{{ form.author }}</span>
                            <span>{{ form.num_pages }}</span>
                            <span>{{ form.date }}</span>
                            <span>{{ form.type_of_book }}</span>
                            <span class="right-0-p">{{ form.favorite_rank }}</span>
                        </div>
                    </div>

                    <div class="booksListRowAdd dsp-block top-15">
                      {{ form.review }}
                      <button type="submit" class="btn-yellow btn-normal btn-xl top-15 w-100">{% trans "Save" %}</button>
                    </div>
                </form>

            </div>
        </div>
    </section>

    {% include 'books/section/particles.html' with one_section=False %}
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/plugin/datepicker/datepicker.min.js' %}"></script>
    <script src="{% static 'js/books.js' %}"></script>
{% endblock %}

templates/books/books.html
{% extends 'base.html' %}

{% load static %}
{% load template_filters %}
{% load i18n %}

{% block title %}
    <title>Book Worms | My Books</title>
{% endblock %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'less/books.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'less/plugin/datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <section class="booksListSection">
        <!-- Messages -->
        {% if messages %}
            {% for message in messages %}
                {% if  message.tags == 'success' %}
                    <div role="alert" class="alert alert-success">
                        <div class="message">{{ message|safe }}</div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
        <!-- End Messages -->

        <div class="container fix-width">
            <div class="booksListTable top bottom-60">
                <form method="POST">{% csrf_token %}
                    <div class="booksListErrorsBlock">
                        {% if form.errors %}
                            {% for field in form %}
                                {% for error in field.errors %}
                                  {{ field.label }}
                                  <span>{{ error|escape }}</span>
                                {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                                 <span>{{ error|escape }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>

                    <div class="booksListRowAdd">
                      <div class="booksListRowAddStep one">
                        <span>{{ form.name }}</span>
                        <span>{{ form.author }}</span>
                        <span><input type="number" name="num_pages" placeholder="{% trans "Pages*" %}" required=""
                                     id="id_num_pages"></span>
                        <span>{{ form.date }}</span>
                        <span>{{ form.type_of_book }}</span>
                        <span>{{ form.favorite_rank }}</span>
                        <a class="btn-green btn-normal btn-green btn-xl w-auto t-a-center" id="next-step-btn">{% trans "Next" %}</a>
                      </div>
                      <div class="booksListRowAddStep two">
                        <span>{{ form.review }}</span>
                        <a class="btn-green btn-normal btn-green btn-xl w-auto t-a-center right-15" id="back-step-btn">{% trans "Back" %}</a>
                        <button type="submit" class="btn-violet btn-normal btn-midnightblue btn-xl">{% trans "Add" %}</button>
                      </div>
                    </div>
                </form>
            </div>

            <div class="flex-row-center-center">
                {% if years|length > 1 %}
                    <ul class="years">
                        <li>{% trans "Please check your year: " %}</li>
                        <li><a href="?year=all" {% if not current_year|is_numeric %}class="active"{% endif %}>
                          {% trans "All books" %}</a></li>
                        {% for year in years %}
                            {% if year == current_year %}
                                <li><a href="?year={{ year }}" class="active">{{ year }}</a></li>
                            {% else %}
                                <li><a href="?year={{ year }}">{{ year }}</a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>

            <div class="booksListTable">
                {% if books %}
                    <div class="booksListHead row">
                        <div class="col-2 col-xl-3">
                            <a href="?order_by=name&year={{ current_year }}">
                                <img src="{% static 'img/direction.svg' %}">
                                <span>{% trans "Name" %}</span>
                            </a>
                        </div>
                        <div class="col-2 col-xl-3">
                            <a href="?order_by=author&year={{ current_year }}">
                                <img src="{% static 'img/direction.svg' %}">
                                <span>{% trans "Author" %}</span>
                            </a>
                        </div>
                        <div class="col-2 col-xl-3">
                            <a href="?order_by=-num_pages&year={{ current_year }}">
                                <img src="{% static 'img/direction.svg' %}">
                                <span>{% trans "Pages" %}</span>
                            </a>
                        </div>
                        <div class="col-2 col-xl-3">
                            <a href="?order_by=-date&year={{ current_year }}">
                                <img src="{% static 'img/direction.svg' %}">
                                <span>{% trans "Date" %}</span>
                            </a>
                        </div>
                        <div class="col-2">
                            <a href="?order_by=-favorite_rank&year={{ current_year }}">
                                <img src="{% static 'img/direction.svg' %}">
                                <span>{% trans "Rating" %}</span>
                            </a>
                        </div>
                    </div>
                    <div class="booksListBody">
                        {% for book in books %}
                            <div class="booksListRowShow row">
                                <b class="booksListRowShowCounter">{{ forloop.revcounter }}</b>
{#                                {{ forloop.revcounter0|add:books.start_index }}#}
                                <div class="col-2 col-xl-3">
                                    <span class="booksListRowShowName">{{ book.name }}</span>
                                </div>
                                <div class="col-2 col-xl-3">
                                    <span class="booksListRowShowAuthor">{{ book.author }}</span>
                                </div>
                                <div class="col-2 col-xl-3"><span>{{ book.num_pages }}</span></div>
                                <div class="col-2 col-xl-3"><span>{{ book.date|date:'c' }}</span></div>
                                <div class="col-2 col-xl-12 booksListRowShowRattingComment">
                                    {#get item return val in dict book.get(name)#}
                                    {#and then list_rating|name#}
                                    <div class="ratting">
                                      {% for i in book_list_rating_by_user|get_item:book.name %}
                                          <img src="{% static 'img/star.svg' %}" class="booksListRowShowStars"
                                               title="{{ book.get_favorite_rank_display }}">
                                      {% endfor %}
                                    </div>

                                    <div class="flex-row-center">
                                        <img src="{% static 'img/utils/books' %}/{{ book.type_of_book }}.svg"
                                             alt="{{ book.get_type_of_book_display }}" title="{{ book.get_type_of_book_display }}">

                                        {% if book.review %}
                                            <span class="comment" style='-webkit-mask: url("{% static 'img/comment.svg' %}") center center'></span>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="booksListRowShowTools col-2 col-xl-12">
                                    <a href="{% url 'book-edit' book.id %}"
                                       class="btn-yellow btn-normal btn-square right-15 flex" title="{% trans "Edit" %}">
                                      <img src="{% static 'img/edit.svg' %}" alt="" width="100%"></a>
                                    <a href="{% url 'book-delete' book.id %}"
                                       class="btn-darkred btn-normal btn-square btn-delete flex" title="{% trans "Delete" %}">
                                        <img src="{% static 'img/bucket.svg' %}" alt="" width="100%"></a>
                                </div>

                                {% if book.review %}
                                    <p class="booksListRowShowComment col-12">{{ book.review }}</p>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>

{#                    <div class="pagination">#}
{#                        <span class="step-links">#}
{#                            {% if books.has_previous %}#}
{#                                <a href="?page={{ books.previous_page_number }}&year={{ current_year }}" class="paginator prev">Prev</a>#}
{#                            {% else %}#}
{#                                <a href="" class="paginator prev disable">Prev</a>#}
{#                            {% endif %}#}
{##}
{#                            {% for page in books.paginator.page_range %}#}
{#                                <a href="?page={{ page }}&year={{ current_year }}" class="paginator#}
{#                                    {% if books.number == page %}active{% endif %}">{{ page }}</a>#}
{#                            {% endfor %}#}
{##}
{#                            {% if books.has_next %} {{ request.year }}#}
{#                                <a href="?page={{ books.next_page_number }}&year={{ current_year }}" class="paginator next">Next</a>#}
{#                            {% else %}#}
{#                                <a href="" class="paginator next disable">Next</a>#}
{#                            {% endif %}#}
{#                        </span>#}
{#                    </div>#}

                {% else %}
                    <div class="booksListNone">
                        <p class="h3">{% trans "Actually you aren't having book right now :(" %}</p>
                    </div>
                {% endif %}
            </div>

        </div>
    </section>

    {% include 'books/section/particles.html' with one_section=False %}
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/plugin/datepicker/datepicker.min.js' %}"></script>
    <script src="{% static 'js/books.js' %}"></script>
{% endblock %}